style: diseño del formulario de configuración del perfil
UnsitosDev/UnsiSmile_front pull request #54
Opened 2024-10-14 01:20 UTC by Getze1221

2024-10-14 02:28 UTC, fr0ste requested changes

2024-10-14 02:28 UTC, fr0ste commented on src/app/components/private/students/components/form-user/form-user.component.html
> +        <li *ngFor="let tab of tabs; let i = index">
ya no se usa *ngFor. puedes usar el comando  ng g @angular/core:control-flow.
para cambiarlo automáticamente

2024-10-20 02:26 UTC, Getze1221 commented on src/app/components/private/students/components/form-user/form-user.component.html
> +        <li *ngFor="let tab of tabs; let i = index">
si ya use el comando y ya quedo 
![Captura de pantalla 2024-10-19 202601](https://github.com/user-attachments/assets/ac1c2759-9d9e-4c9e-b03b-27526b159056)

2024-10-20 17:40 UTC, fr0ste approved these changes
soso

2024-10-20 17:40 UTC, merged